version: '3'
services:
  app:
    image: jbostrom/rotgrind-bingo:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/rotbingo/nginx:/etc/nginx
      - /var/rotbingo/certs:/etc/ssl/private
  certbot:
    image: certbot/certbot